version: '3.4'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web-root:/var/www/html
      - ./nginx:/etc/nginx/conf.d
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nginx
    volumes:
      - ./web-root:/var/www/html
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
