namespace WebApp.Cms;

public class GeneralSettings : DatabaseConnected
{
    public string SystemName { get; set; } = "PD CMS";
    public string Logo { get; set; } = "core/logo.png";
    public string TermsOfService { get; set; } = "<h1>Terms of service</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus pharetra ultricies ex, ut vehicula purus interdum non. Nulla ac lectus vel libero semper congue. Ut purus urna, volutpat quis mauris ut, cursus ultrices quam. Sed vehicula feugiat dui euismod ornare. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras pulvinar semper feugiat. Morbi urna mauris, tempus id scelerisque ut, tristique et diam. Nunc malesuada a felis nec congue.</p>\r\n<p>Mauris non ligula justo. Sed vel laoreet massa. Nullam sit amet tellus cursus, pulvinar est ac, volutpat risus. Vestibulum eleifend pellentesque neque, vel porta libero consequat sed. Donec vitae pharetra arcu. Vestibulum vel tincidunt purus. Suspendisse sit amet dui at neque tincidunt dapibus. Vivamus elementum accumsan odio a ullamcorper.</p>\r\n<p>Nunc lobortis fermentum ante, eget elementum justo fermentum ut. Suspendisse potenti. Nulla ullamcorper scelerisque ex, vel auctor nisi suscipit finibus. Quisque in risus sed justo maximus scelerisque ut blandit felis. Curabitur porttitor aliquam odio. Integer venenatis, libero sit amet convallis convallis, neque sapien iaculis enim, ac malesuada felis turpis quis nulla. Nulla sed enim ac mi pharetra luctus ornare quis libero. Duis nec vestibulum mauris. Sed venenatis varius mattis. Phasellus sit amet justo ut velit feugiat commodo id eu tellus. Nulla facilisi. Cras luctus nulla ut lorem euismod pretium. Cras auctor tellus in convallis hendrerit.</p>\r\n<p>Proin feugiat pulvinar elit, eu tincidunt quam ullamcorper sed. Morbi viverra ex eget arcu volutpat hendrerit. Proin pulvinar, sem eu porta sagittis, nunc erat vestibulum dui, quis congue augue lectus vehicula urna. Curabitur sagittis viverra leo nec luctus. Mauris rutrum maximus lacus, eu interdum turpis pulvinar quis. Maecenas quis nisl ut nibh pretium egestas. Vestibulum sem odio, posuere nec magna nec, pulvinar tempor massa. Vivamus non hendrerit metus. Duis sed porttitor erat, sit amet facilisis lacus. Aenean fermentum, sapien a lobortis mollis, libero ante ullamcorper magna, nec placerat urna lacus non est. Aliquam eleifend tincidunt ex, non facilisis sapien scelerisque at. Fusce quis pellentesque arcu. Phasellus et euismod diam. Pellentesque pharetra porttitor orci, ullamcorper dictum sapien dapibus quis.</p>\r\n<p>Mauris a tristique urna. Sed porta, purus nec convallis sollicitudin, nisl risus porttitor quam, at porta purus nulla in libero. Suspendisse at sapien neque. In tristique sapien neque, et ullamcorper elit maximus egestas. Nulla sollicitudin egestas purus vel varius. Nam posuere ultrices turpis, vitae accumsan ligula luctus non. Aliquam ac eros velit.</p>";
    public string Contact { get; set; } = "<h1>Contact</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus pharetra ultricies ex, ut vehicula purus interdum non. Nulla ac lectus vel libero semper congue. Ut purus urna, volutpat quis mauris ut, cursus ultrices quam. Sed vehicula feugiat dui euismod ornare. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras pulvinar semper feugiat. Morbi urna mauris, tempus id scelerisque ut, tristique et diam. Nunc malesuada a felis nec congue.</p>\r\n<p>Mauris non ligula justo. Sed vel laoreet massa. Nullam sit amet tellus cursus, pulvinar est ac, volutpat risus. Vestibulum eleifend pellentesque neque, vel porta libero consequat sed. Donec vitae pharetra arcu. Vestibulum vel tincidunt purus. Suspendisse sit amet dui at neque tincidunt dapibus. Vivamus elementum accumsan odio a ullamcorper.</p>\r\n<p>Nunc lobortis fermentum ante, eget elementum justo fermentum ut. Suspendisse potenti. Nulla ullamcorper scelerisque ex, vel auctor nisi suscipit finibus. Quisque in risus sed justo maximus scelerisque ut blandit felis. Curabitur porttitor aliquam odio. Integer venenatis, libero sit amet convallis convallis, neque sapien iaculis enim, ac malesuada felis turpis quis nulla. Nulla sed enim ac mi pharetra luctus ornare quis libero. Duis nec vestibulum mauris. Sed venenatis varius mattis. Phasellus sit amet justo ut velit feugiat commodo id eu tellus. Nulla facilisi. Cras luctus nulla ut lorem euismod pretium. Cras auctor tellus in convallis hendrerit.</p>\r\n<p>Proin feugiat pulvinar elit, eu tincidunt quam ullamcorper sed. Morbi viverra ex eget arcu volutpat hendrerit. Proin pulvinar, sem eu porta sagittis, nunc erat vestibulum dui, quis congue augue lectus vehicula urna. Curabitur sagittis viverra leo nec luctus. Mauris rutrum maximus lacus, eu interdum turpis pulvinar quis. Maecenas quis nisl ut nibh pretium egestas. Vestibulum sem odio, posuere nec magna nec, pulvinar tempor massa. Vivamus non hendrerit metus. Duis sed porttitor erat, sit amet facilisis lacus. Aenean fermentum, sapien a lobortis mollis, libero ante ullamcorper magna, nec placerat urna lacus non est. Aliquam eleifend tincidunt ex, non facilisis sapien scelerisque at. Fusce quis pellentesque arcu. Phasellus et euismod diam. Pellentesque pharetra porttitor orci, ullamcorper dictum sapien dapibus quis.</p>\r\n<p>Mauris a tristique urna. Sed porta, purus nec convallis sollicitudin, nisl risus porttitor quam, at porta purus nulla in libero. Suspendisse at sapien neque. In tristique sapien neque, et ullamcorper elit maximus egestas. Nulla sollicitudin egestas purus vel varius. Nam posuere ultrices turpis, vitae accumsan ligula luctus non. Aliquam ac eros velit.</p>";
    public bool AutoReport { get; set; } = false;
    public int AutoReportReputation { get; set; } = 0;
    public int ReputationUnlisted { get; set; } = 100;
    public int StartingReputation { get; set; } = 1000;
    public string MainColor { get; set; } = "#194d33";
    public string MainColorFont { get; set; } = "#ffffff";

    public GeneralSettings() { }

    public GeneralSettings(string systemName, string logo, string termsOfService, string contact, bool autoReport, int autoReportReputation, int reputationUnlisted, int startingReputation) 
    {
        SystemName = systemName;
        Logo = logo;
        TermsOfService = termsOfService;
        Contact = contact;
        AutoReport = autoReport;
        AutoReportReputation = autoReportReputation;
        ReputationUnlisted = reputationUnlisted;
        StartingReputation = startingReputation;
    }
}