name: Create images and publish

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  Image_creation_and_publication:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set version (stable)
      if: ${{ github.ref_type == 'tag' }}
      run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
    - name: Set version (development)
      if: ${{ github.ref_type == 'branch' }}
      run: echo "VERSION=dev" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/pd-webapp:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/pd-webapp:${{ env.VERSION }}
          ghcr.io/${{ github.repository_owner }}/pd-webapp:latest
          ghcr.io/${{ github.repository_owner }}/pd-webapp:${{ env.VERSION }}
        file: ./PD/WebApp/Dockerfile
        context: ./PD
