name: Run tests

on: [workflow_dispatch, workflow_call]

env:
  DOTNET_VERSION: '6.0.401'

jobs: 
  Unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Run tests
      run: dotnet test "./PD/Tests"
